name: Deploy via SSH script

on: [push, pull_request]
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script via SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ~/deploy-staging/deploy-eskergames.sh ${{ github.ref_name }}
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
